// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxK-tudJz88ahYqmJQwY_jnr8HSklZgtA',
    appId: '1:605199851002:web:d543d105ba8d7eb448d843',
    messagingSenderId: '605199851002',
    projectId: 'beauty-contest-d74dd',
    authDomain: 'beauty-contest-d74dd.firebaseapp.com',
    storageBucket: 'beauty-contest-d74dd.appspot.com',
    measurementId: 'G-X39XJ1CYTT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH_iwYTVgCsk_j_waGBf3-W-urF4yMJgE',
    appId: '1:605199851002:android:21c2d6ef3b1422e048d843',
    messagingSenderId: '605199851002',
    projectId: 'beauty-contest-d74dd',
    storageBucket: 'beauty-contest-d74dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfpR9dsqXb6H9_RDNQ_pVgYpE0cixEvuI',
    appId: '1:605199851002:ios:4f00f0ce688205cd48d843',
    messagingSenderId: '605199851002',
    projectId: 'beauty-contest-d74dd',
    storageBucket: 'beauty-contest-d74dd.appspot.com',
    iosBundleId: 'com.prosperplay.beautyContestAdmin',
  );
}
